robot_9:
  communication_node_robot_9:
    ros__parameters:
      robot_name: "robot_9"
      robot_ip: "192.168.0.56"
      communication_port: 8081

robot_1:
  communication_node_robot_1:
    ros__parameters:
      robot_name: "gancho"
      robot_ip: "0,0,0,0"
      communication_port: 8000

