localization_node_robot1:
  ros__parameters:
    frame_prefix: 'robot1'

localization_node_robot2:
  ros__parameters:
    frame_prefix: 'robot2'

localization_node_robot3:
  ros__parameters:
    frame_prefix: 'robot3'